@startuml
left to right direction

actor Professor
actor Aluno
actor Administrador

rectangle "Sistema de Controle e Gerenciamento de Cursos Livres" {

    usecase "Realizar cadastros diversos" as UC1
    usecase "Cadastrar-se" as UC1a
    usecase "Cadastrar Aluno" as UC1b
    usecase "Login" as UC2
    usecase "Criar Curso" as UC3
    usecase "Gerenciar Curso" as UC4
    usecase "Editar Curso" as UC4a
    usecase "Remover Curso" as UC4b
    usecase "Acompanhar Progresso" as UC6
    usecase "Gerenciar Pagamentos" as UC7
    usecase "Analisar Desempenho" as UC8
    usecase "Análise por Aluno" as UC8a
    usecase "Gerenciar Sistema" as UC11
    usecase "Configurar Permissões" as UC11a
    usecase "Cadastrar Professor" as UC12
    usecase "Emitir Relatórios" as UC10

    Professor --> UC1b
    Professor --> UC2
    Professor --> UC3
    Professor --> UC4
    UC4 --> UC4a : <<include>>
    UC4 --> UC4b : <<include>>
    Professor --> UC7
    Professor --> UC8
    Professor --> UC10
    UC8 --> UC8a : <<extends>>

    Aluno --> UC2
    Aluno --> UC6

    Administrador --> UC1a
    Administrador --> UC11
    Administrador --> UC12
    Administrador --> UC1
    UC11 --> UC11a : <<include>>


    Administrador --|> Professor : <<extends>>
}
@enduml
