@startuml
left to right direction

actor Professor
actor Aluno
actor Administrador

rectangle "Sistema de Controle e Gerenciamento de Cursos Livres" {

    usecase "Cadastrar-se" as UC1
    usecase "Login" as UC2
    usecase "Criar Curso" as UC3
    usecase "Administrar Curso" as UC4
    usecase "Matricular-se no Curso" as UC5
    usecase "Acompanhar Progresso" as UC6
    usecase "Gerenciar Pagamentos" as UC7
    usecase "Analisar Desempenho" as UC8
    usecase "Avaliar Curso" as UC9
    usecase "Suporte Técnico" as UC10
    usecase "Gerenciar Sistema" as UC11

    Professor --> UC1
    Professor --> UC2
    Professor --> UC3
    Professor --> UC4
    Professor --> UC7
    Professor --> UC8
    Professor --> UC10

    Aluno --> UC1
    Aluno --> UC2
    Aluno --> UC5
    Aluno --> UC6
    Aluno --> UC9
    Aluno --> UC10

    Administrador --> UC2
    Administrador --> UC7
    Administrador --> UC11
    Administrador --> UC10
}

@enduml
