@startuml


actor "Professor" as professor
actor "Aluno" as aluno

rectangle Sistema {
    usecase "Cadastro de professores" as UC1
    usecase "Cadastro de alunos" as UC2
    usecase "Criação de cursos" as UC3
    usecase "Administração de cursos" as UC4
    usecase "Matrícula de alunos" as UC5
    usecase "Acompanhamento de desempenho" as UC6
    usecase "Gestão financeira" as UC7
    usecase "Análise de cursos" as UC8
}

professor -> UC1 : Realiza
professor -> UC3 : Cria
professor -> UC4 : Administra
professor -> UC6 : Acompanha
professor -> UC7 : Gerencia
professor -> UC8 : Analisa

aluno -> UC2 : Realiza
aluno -> UC5 : Matricula
aluno -> UC6 : Acompanha

@enduml
